[Desktop Entry]
Name=LaGaDesk-N12-R
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=LaGaDesk-N12-R
MetacityTheme=LaGaDesk-N12-R
IconTheme=LaGaDesk-BlackWhite-Red
GtkColorScheme=fg_color:#B7B7B7,bg_color:#2B2B2B,base_color:#191919,text_color:#8E8E8E,selected_bg_color:#777777,selected_fg_color:#ffffff,tooltip_bg_color:#d7d7d7,tooltip_fg_color:#000000
CursorTheme=oxy-grey
CursorSize=24
NotificationTheme=ubuntu
